### PR TITLE
This repo is the legit one, I can confirm

### PR DESCRIPTION
**Pull request by RedDaedalus**
If you've stumbled upon this looking for lavalink's GitHub, you can find it here: https://github.com/Frederikam/Lavalink

### CODE REVIEW

**Comment by h-exx** [comment]
+1

**Comment by Coolguy3289** [comment]
+1

**Review by Danix421 — APPROVED** [review]

**Comment by Asthriona** [comment]
what happened to the OG one? :o

**Review by jacany — APPROVED** [review]
Certified.

**Comment by Danix421** [comment]
It looks like the repo owner account is shutdown, so... I think this has to be closed.

**Comment by jacany** [comment]
eh who cares, leave this open so people who find this repo see this pull, and can go to the correct repo.
also shows how damn annoying the person who owns this account is, kind of outragous that the first result for a decently sized project on google is an empty repository with "OwO, what's this" as it's readme, and no links.

**Comment by BrianWasTaken** [comment]
what happened? I thought this repository used to be the parent lavalink repository...

**Comment by BrianWasTaken** [comment]
oh wait i think i found the repository: https://github.com/freyacodes/Lavalink
they renamed their account username, that's why.

**Comment by Asthriona** [comment]
> oh wait i think i found the repository: https://github.com/freyacodes/Lavalink
> they renamed their account username, that's why.

That's the right one indeed. 
Wish the new creator of this account adds a link would be great. on Google stop indexing it. 
eh... Troll gonna troll I guess.

**Comment by BrianWasTaken** [comment]
> > oh wait i think i found the repository: https://github.com/freyacodes/Lavalink
> > they renamed their account username, that's why.
> 
> That's the right one indeed.
> Wish the new creator of this account adds a link would be great. or Google stop indexing it.
> eh... Troll gonna troll I guess.

yeah it's kinda annoying tbh, I really thought the developer archived or yeah, shut down.

**Review by Asthriona — APPROVED** [review]

**Review by Silverdimond — APPROVED** [review]

**Comment by ItzOnlyAnimal** [comment]
OwO what's this

**Comment by Asthriona** [comment]
> OwO what's this

a very annoying repo. Nothing else.

**Comment by rowansc1** [comment]
Wow gotta love it when people change their name haha!

**Review by exiify — APPROVED** [review]
best change of the century!

**Review by ZandercraftGames — APPROVED** [review]
Some person is obviously trying to misguide people. They copied the username and repo name to use the same link.

**Review by shidemuri — APPROVED** [review]

**Review by Xenfo — APPROVED** [review]

**Review by exiify — CHANGES_REQUESTED** [review]
Bad

**Comment by Frederikam** [comment]
> 
> 
> It looks like the repo owner account is shutdown, so... I think this pull request has to be closed.

true

**Comment by Silverdimond** [comment]
why are you hurting people by suppressing the fact that the maintainer of lavalink changed their username?

**Comment by Asthriona** [comment]
> > It looks like the repo owner account is shutdown, so... I think this pull request has to be closed.
> 
> true

Wrong. They renamed. Please merge the PR.

**Comment by exiify** [comment]
Why are you guys replying to this guy? He is just a troll; your just giving him what he wants, which is attention. He isn't going to change this repo name anytime soon.

**Comment by Asthriona** [comment]
> Why are you guys replying to this guy? He is just a troll; your just giving him what he wants, which is attention. He isn't going to change this repo name anytime soon.

Pass the time, May help other, and I mean, everyone need a bit of attention sometimes :)

**Pull request closed without merging**
