### PR TITLE
Add link to the real repo.

### PR DESCRIPTION
**Pull request by Asthriona**
The owner of Lavalink renamed, someone took this name and make this repo just to be annoying. 
if you want the real Lavalink please follow this link: https://github.com/freyacodes/Lavalink

This repo is very annoying, mostly for new users. Please merge it, or replace the actual content of the [README.MD](https://github.com/Frederikam/Lavalink/blob/main/README.md) by the link of the real repo.

Original edits by #1

### CODE REVIEW

**Comment by exiify** [comment]
this really doesn't do anything

**Comment by Silverdimond** [comment]
> this really doesn't do anything 

How so?

**Comment by gamescom15** [comment]
The first result when you search for "lavalink" is this repo, and it's clear that people mean the original one.

**Comment by Asthriona** [comment]
> The first result when you search for "lavalink" is this repo, and it's clear that people mean the original one.

Just the fact the real owner is not mentioned or anything is bad. adding the .jar to the repo is no help, Thats actually a security issue. 
> this really doesn't do anything
do you know if the file has been modified?
is there any security patch this version doesn't have?
I mean that's some serious concern. 
Imma Email FreyaCodes, cuz Github support is no help. 

Also, I don't really appreciate the coms editing by the owner of this repo. 

Owner Edits
imo no one else than the comment's author should be able to edit them.

**Pull request closed without merging**
